name: Tests
on: push

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
      OTP_VERSION: '24.0'
      ELIXIR_VERSION: '1.13.2'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ env.OTP_VERSION }}
        elixir-version: ${{ env.ELIXIR_VERSION }}
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
          _build
          deps
        key: mix-lock-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-${{ hashFiles('mix.lock') }}
    - name: Fetch Dependencies
      run: mix do deps.get
    - name: Enforce Coding Styles
      run: mix format --check-formatted
    - name: Run Tests and Report to Coveralls
      run: mix coveralls.github
